config/routes.rb
Rails.application.routes.draw do
  namespace :api, constraints: {format: :json} do
    namespace :v1 do
      devise_for :users, :controllers => { :registrations => "api/v1/registrations", :sessions=> "api/v1/sessions" }
      resources :users
      resources :posts do
        resources :comments
    end
  end
  end
 
  devise_for :users
  resources :users
  resources :posts do
    resources :comments
end
 root 'posts#index'

   resources :users  do
    collection do
      get :search

    end
  end

  resources :friendships

end

app/models/user.rb
require 'securerandom'
class User < ActiveRecord::Base

  before_create :set_auth_token

	has_many :friendships
  has_many :friends, :through => :friendships
	has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user

	has_one :profile
	has_many :posts
	has_many :comments
	has_attached_file :image, styles: { large: "300x300", medium: "100x100#", thumb: "50x50#"}
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me, :firstname, :lastname, :image


 
def active?
  !!active
end

def inactive_message
  "Sorry, this account has been deactivated."
end

def soft_delete
  # assuming you have deleted_at column added already
  update_attribute(:deleted_at, Time.current)
  update_attribute(:active, false)
end


def friend_with?(user)
  friendships.find_by(friend_id: user.id)
end

private

  def set_auth_token
    return if auth_token.present?
    self.auth_token = generate_auth_token
  end

  def generate_auth_token
    SecureRandom.uuid.gsub(/\-/,)
  end


end

app/controllers/api/v1/users_controller.rb
module Api
  module V1

    class UsersController < ApplicationController
    protect_from_forgery
    respond_to :json 
   
    def index
      # @users = User.all
      respond_with User.all
      # respond_to do |format|
      #   format.json { render json: @users }
      #   format.xml { render xml: @users }
      
    end

    def show
  	  respond_with User.find(params[:id])
    end

    def update
      @user = User.find(params[:id])
      if @user.update(user_params)
         render :json=> @user.as_json(:email=>@user.email), :status=>200
      else
          warden.custom_failure!
          render :json=> user.errors, :status=>204
      end
    end

    def edit
    
    end
    
    private

    def user_params
      params.require(:user).permit(:firstname, :lastname, :email)
    end

    def find_user
      @user = User.find(params[:id])     
    end
    end

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
   # @user = current_user
   # @posts = @user.posts
    @user = User.find(params[:search])
    @posts = @user.posts
  end

  def show
  	@user = User.find(params[:id])
  	@posts = @user.posts
  end

  def add_friend
    
  end
  
  def remove_friend
    
  end

end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<html><body>

<%= link_to "Add Friend", friendships_path(:friend_id => @user), :method => :post, :class => "addBtn"  %>

<section id = "profileHeader">
<h1 align="center"><%= @user.firstname %> <%= @user.lastname %></h1>
	<div class="profileimg">
		<center>
		<%= image_tag @user.image.url(:medium), class: "img-circle" %>
	</div>
</section>

<section id = "allposts">
<div class = "postsLabel">
<h2 align="center"><%= @user.firstname %>'s Posts</h2>
</div>
	<% @posts.each do |post| %>
	<center>
	<div class="col-md-4">
 	<h2 class="status"><%= post.status %></h2>
 	<%= link_to "View Comments", post_path(post), class: "btn-viewcomment" %> 
 	</div> 
    <% end %>
</section>

<section id = "friends">
<div class = "friendsLabel">
<br>
<h2 align="center"><%= @user.firstname %>'s Friends</h2>
</div>

<div class = "friendsList">
	<% for friendship in @user.friendships %>
  		<%= image_tag friendship.friend.image.url(:thumb), :class => "friendImage" %>
    	<%= link_to "#{friendship.friend.firstname} #{friendship.friend.lastname}", friendship, :class => "friendName"%>
		(<%= link_to "remove", friendship, :method => :delete %>)
  	<% end %> 
  	</div> 
<div class = "postsLabel">
<br>
<h2>Users Who Have Befriended <%= @user.firstname %></h2>
</div>
<ul>
  <% for user in @user.inverse_friends %>
  <%= image_tag user.image.url(:thumb), :class => "friendImage" %>
  <%= link_to "#{user.firstname} #{user.lastname}", user, :class => "friendName" %>
  <% end %>
</ul>
</section> 

app/views/users/show.html.erb
<html><body>


<% if @user != current_user %>
<%= link_to "Add Friend", friendships_path(:friend_id => @user), :method => :post, :class => "addBtn", :onclick => "alert('Friend added!')" %>
<% else %>

<% end %> 


<section id = "profileHeader">
<h1 align="center"><%= @user.firstname %> <%= @user.lastname %></h1>
	<div class="profileimg">
		<center>
		<%= image_tag @user.image.url(:medium), class: "img-circle" %>
	</div>
</section>

<section id = "allposts">
<div class = "postsLabel">
<h2 align="center"><%= @user.firstname %>' Posts</h2>
</div>
	<% @posts.each do |post| %>
	<center>
	<div class="col-md-4">
 	<h2 class="status"><%= post.status %></h2>
 	<%= link_to "View Comments", post_path(post), class: "btn-viewcomment" %> 
 	</div> 
    <% end %>
</section>

<section id = "friends">
<div class = "friendsLabel">
<br>
<h2 align="center"><%= @user.firstname %>' Friends</h2>
</div>

<div class = "friendsList">
	<% for friendship in @user.friendships %>
  		<%= image_tag friendship.friend.image.url(:thumb), :class => "friendImage" %>
    	<%= link_to "#{friendship.friend.firstname} #{friendship.friend.lastname}", friendship, :class => "friendName"%>
		(<%= link_to "remove", friendship, data: { confirm: "Are you sure you want to remove your friend?" }, method: :delete %>)
  	<% end %> 
  	</div> 
<div class = "postsLabel">
<br>
<h2>Users Who Have Befriended <%= @user.firstname %></h2>
</div>
<ul>
  <% for user in @user.inverse_friends %>
  <%= image_tag user.image.url(:thumb), :class => "friendImage" %>
  <%= link_to "#{user.firstname} #{user.lastname}", user, :class => "friendName" %>
  <% end %>
</ul>
</section> 